### ISSUE TITLE
Reference error in handleErrors

### ISSUE THREAD

**Issue by marcuswhybrow** [kadirahq/lokka-transport-http#18]
Encountering a transport error results in...

```
data is not defined
```

Looks like `data` isn't defined here:

https://github.com/kadirahq/lokka-transport-http/blob/v1.6.0/lib/index.js#L28

**Comment by arunoda** [comment]
That's a huge error. I'll fix it now.

**Comment by arunoda** [comment]
Did a fix for this and released as `v1.6.1`
