### ISSUE TITLE
Use window.fetch instead of setting global variable fetch

### ISSUE THREAD

**Issue by mtsewrs** [kadirahq/lokka-transport-http#3]
When testing with phantomjs it throws an error on global variables

**Comment by arunoda** [comment]
Can I have the exact error?

**Comment by arunoda** [comment]
I've published a new version with a potential fix. Give it a try.

**Comment by mtsewrs** [comment]
@arunoda Great, now working! Thanks!

**Comment by arunoda** [comment]
Awesome.
